name: Compile AHKV2 Script
description: GitHub Action to compile AutoHotKey V2 scripts using Ahk2Exe
author: alfvar , CCCC-L, nekocodeX

inputs:
  token:
    description: GitHub personal access token
    default: ${{ github.token }}
  in:
    description: Path of the script to compile
    required: true
  out:
    description: Output EXE path (optional)
    required: false
  base:
    description: Compile bitness (32|64)
    required: false
    default: 64
  icon:
    description: Path to .ico file (optional)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set WORKING_DIRECTORY
      shell: pwsh
      run: |
        $cwd = "${{ runner.temp }}"

        
    - name: Install AutoHotkey + Ahk2Exe
      shell: pwsh
      run: |
        $wd = $env:WORKING_DIRECTORY

        $headers = @{
          Authorization = "Bearer $env:token"
          "Content-Type" = "application/json"
        }
        
        # Download and extract AutoHotkey
        $uri = "https://api.github.com/repos/AutoHotkey/AutoHotkey/releases/latest"
        $ahkRelease = Invoke-RestMethod -Uri $uri -Headers $headers
        $ahkZip = Join-Path $wd "autohotkey.zip"
        Invoke-WebRequest $ahkRelease.assets[0].browser_download_url -OutFile $ahkZip

        # Download and extract Ahk2Exe
        $compilerRelease = Invoke-RestMethod "https://api.github.com/repos/AutoHotkey/Ahk2Exe/releases/latest"
        $compilerAsset = $compilerRelease.assets | Select-Object -First 1
        $compilerZip = Join-Path $wd "ahk2exe.zip"
        Invoke-WebRequest $compilerAsset.browser_download_url -OutFile $compilerZip

        # Extract both
        Expand-Archive $ahkZip -DestinationPath "$wd\AutoHotkey" -Force
        Expand-Archive $compilerZip -DestinationPath "$wd\AutoHotkey\Compiler" -Force
        Remove-Item $ahkZip, $compilerZip -Force

        # Add to PATH and export ahkEXE
        "ahkCompiler=$wd\AutoHotkey\Compiler\Ahk2Exe.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        "ahkBase=$wd\AutoHotkey\AutoHotkey${{ inputs.base }}.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      env:
        token: ${{ inputs.token }}

    - name: Compile script with Ahk2Exe
      shell: pwsh
      run: |
        $cmd = "`"$env:ahkCompiler`" /silent verbose"
        
        $in = "${{ inputs.in }}"
        $cmd += " /in `"$in`""

        # Handle optional icon
        $icon = if ("${{ inputs.icon }}") {
          "${{ inputs.icon }}"
        } else {
          [System.IO.Path]::ChangeExtension($in, ".ico")
        }
        $cmd += " /icon `"$icon`""

        # Optional output
        if ("${{ inputs.out }}") {
          $cmd += " /out `"$("${{ inputs.out }}")`""
        }

        # Optional base
        if ("${{ inputs.base }}") {
          $cmd += " /base `"$env:ahkBase`""
        }

        Write-Host "Running: $cmd"
        Invoke-Expression $cmd
