name: Compile AHKV2 Script
description: GitHub Action to compile AutoHotKey V2 scripts using Ahk2Exe
author: CCCC-L, nekocodeX

inputs:
  in:
    description: The path and name of the script to compile
    required: true
  out:
    description: The path\name of the output .exe to be created
    required: false
  base:
    description: compile bit number 32|64
    required: false
    default: 64
  icon:
    description: The path and name of the icon file
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install AutoHotkey
      shell: pwsh
      run: |
        $wd = (Get-Item .).FullName
        Invoke-WebRequest (Invoke-RestMethod https://api.github.com/repos/AutoHotkey/AutoHotkey/releases/latest).assets[0].browser_download_url -OutFile "$wd\autohotkey.zip";
        $response = Invoke-RestMethod "https://api.github.com/repos/AutoHotkey/Ahk2Exe/releases/latest"
        foreach ($asset in $response[0].assets) {
          $url = $asset.browser_download_url
        }
        Invoke-WebRequest $url -OutFile "$wd\autohotkey2exe.zip";
        
        Expand-Archive -Path "$wd\autohotkey.zip" -DestinationPath "$wd\autoHotkey\" -Force;
        Expand-Archive -Path "$wd\autohotkey2exe.zip" -DestinationPath "$wd\autoHotkey\Compiler" -Force;
        Remove-Item -Path "$wd\autohotkey.zip" -Force
        Remove-Item -Path "$wd\autohotkey2exe.zip" -Force
        Write-Output ("$wd\autohotkey\;" + "$wd\autohotkey\Compiler") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Write-Output ("BaseFile=$wd\autohotkey\AutoHotkey${{inputs.base}}.exe") | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Run AHK2Exe
      shell: pwsh
      run: |
        $command = 'ahk2exe.exe verbose '
        if('${{inputs.in}}' -ne ''){
          $command += '/in "${{inputs.in}}" '
          if('${{inputs.icon}}' -eq ''){
            $icon = [System.IO.Path]::ChangeExtension('${{inputs.in}}', '.ico')
          } else {
            $icon = '${{inputs.icon}}'
          }
          $command += '/icon "$icon" '
        }
        if('${{inputs.out}}' -ne ''){
          $command += '/out "${{inputs.out}}" '
        }
        if('${{inputs.base}}' -ne ''){
          $command += '/base "$Env:BaseFile" '
        }
        Write-Output $command